# Generated by Django 4.0.2 on 2022-03-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_membro_temporario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodespesa',
            name='variavel',
            field=models.BooleanField(default=False, verbose_name='Variável'),
        ),
    ]
