# Generated by Django 4.0.2 on 2022-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_tipodespesa_variavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='extra',
            field=models.BooleanField(default=False, verbose_name='Extra'),
        ),
        migrations.AddField(
            model_name='tipodespesa',
            name='extra',
            field=models.BooleanField(default=False, verbose_name='Extra'),
        ),
    ]
