# Generated by Django 4.0.2 on 2022-04-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_membro_extra_tipodespesa_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='tipodespesa',
            name='extra',
        ),
    ]
