# Generated by Django 4.0.2 on 2022-05-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_dependente_membro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodespesa',
            name='proporcional',
            field=models.BooleanField(default=False, verbose_name='Proporcional'),
        ),
    ]
