# Generated by Django 4.0.2 on 2022-03-20 14:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('mes', models.IntegerField(default='03', verbose_name='Mês')),
                ('ano', models.IntegerField(default='2022', verbose_name='Ano')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Parcelamento',
                'verbose_name_plural': 'Parcelamentos',
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('numero', models.IntegerField(default=0, verbose_name='Numero da Parcela')),
                ('vencimento', models.DateField(default=datetime.datetime(2022, 3, 20, 11, 29, 5, 177459), verbose_name='Data Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('membro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadastros.membro')),
                ('parcelamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='financeiro.parcelamento', verbose_name='Parcelamento')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
            },
        ),
        migrations.CreateModel(
            name='DespesaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.despesa', verbose_name='Despesa')),
                ('tipodespesa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastros.tipodespesa', verbose_name='Tipo Despesa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Despesa Item',
                'verbose_name_plural': 'Despesas Itens',
                'ordering': ['descricao'],
            },
        ),
    ]
