# Generated by Django 4.0.2 on 2022-03-20 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='vencimento',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 11, 29, 42, 477916), verbose_name='Data Vencimento'),
        ),
    ]
