# Generated by Django 4.0.2 on 2022-03-20 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_parcela_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='vencimento',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 11, 33, 41, 544030), verbose_name='Data Vencimento'),
        ),
    ]
