# Generated by Django 4.0.2 on 2022-03-20 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_membro_temporario'),
        ('financeiro', '0003_alter_parcela_vencimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcela',
            options={'ordering': ['parcelamento', 'numero'], 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.AlterField(
            model_name='parcela',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastros.membro', verbose_name='Mebro'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='vencimento',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 11, 42, 59, 787749), verbose_name='Data Vencimento'),
        ),
    ]
