# Generated by Django 4.0.2 on 2022-03-20 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_parcela_options_alter_parcela_membro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='vencimento',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 11, 49, 15, 214675), verbose_name='Data Vencimento'),
        ),
    ]
