# Generated by Django 4.0.2 on 2022-03-20 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_parcela_pago_alter_parcela_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='vencimento',
            field=models.DateField(default='2022-01-01', verbose_name='Data Vencimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcela',
            name='vencimento',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 16, 45, 27, 396607), verbose_name='Data Vencimento'),
        ),
    ]
