# Generated by Django 4.0.2 on 2022-03-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_membro_temporario'),
        ('financeiro', '0006_parcelamento_vencimento_alter_parcela_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastros.membro', verbose_name='Membro'),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='vencimento',
            field=models.DateField(verbose_name='Data Vencimento'),
        ),
        migrations.CreateModel(
            name='DespesaParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('datapagamento', models.DateField(verbose_name='Data Pagamento')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.despesa', verbose_name='Despesa')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cadastros.membro', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Despesa Parcela',
                'verbose_name_plural': 'Despesa Parcelas',
                'ordering': ['despesa'],
            },
        ),
    ]
