# Generated by Django 4.0.2 on 2022-04-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_despesaparcela_datapagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='mes',
            field=models.IntegerField(default='04', verbose_name='Mês'),
        ),
    ]
