# Generated by Django 4.0.2 on 2022-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_alter_despesa_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='mes',
            field=models.IntegerField(default='05', verbose_name='Mês'),
        ),
    ]
