# Generated by Django 4.0.2 on 2022-05-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_dependente_membro'),
        ('reservas', '0002_reservadependente'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dependente',
            field=models.ManyToManyField(to='cadastros.Dependente'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='membro',
            field=models.ForeignKey(limit_choices_to={'temporario': False}, on_delete=django.db.models.deletion.RESTRICT, to='cadastros.membro', verbose_name='Membro'),
        ),
    ]
