# Generated by Django 4.0.2 on 2022-05-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_dependente_alter_reserva_membro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='dependente',
        ),
    ]
